"""SPICE export for PIC graphs (v0.1).

This is an interoperability seam, not a claim that ngspice can "solve optics"
out of the box.

What this does provide:
- A deterministic, reviewable netlist representation of graph connectivity.
- A stable mapping file that ties (node, port) terminals to SPICE nets.
- A hook for partners/customers to swap in foundry/EDA subcircuit libraries.
"""

from __future__ import annotations

import json
import platform
import re
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from photonstrust.components.pic.library import component_ports
from photonstrust.graph.compiler import compile_graph
from photonstrust.graph.schema import validate_graph
from photonstrust.utils import hash_dict


_SANITIZE_RE = re.compile(r"[^A-Za-z0-9_]+")


def _spice_ident(s: str) -> str:
    s = str(s).strip()
    if not s:
        return "X"
    out = _SANITIZE_RE.sub("_", s)
    if not out:
        out = "X"
    if out[0].isdigit():
        out = "n_" + out
    return out


@dataclass
class _UF:
    parent: dict[tuple[str, str], tuple[str, str]]

    def find(self, x: tuple[str, str]) -> tuple[str, str]:
        p = self.parent.get(x, x)
        if p == x:
            self.parent[x] = x
            return x
        root = self.find(p)
        self.parent[x] = root
        return root

    def union(self, a: tuple[str, str], b: tuple[str, str]) -> None:
        ra = self.find(a)
        rb = self.find(b)
        if ra == rb:
            return
        # Deterministic root choice (lexicographic).
        ka = (ra[0].lower(), ra[1].lower())
        kb = (rb[0].lower(), rb[1].lower())
        if ka <= kb:
            self.parent[rb] = ra
        else:
            self.parent[ra] = rb


def export_pic_graph_to_spice_artifacts(
    request: dict[str, Any],
    output_dir: str | Path,
    *,
    require_schema: bool = False,
) -> dict[str, Any]:
    """Export a PIC graph to SPICE netlist + mapping artifacts.

    Request (v0.1):
      - graph: PhotonTrust graph dict (profile=pic_circuit)
      - settings:
        - top_name?: str (default: PT_TOP)
        - subckt_prefix?: str (default: PT)
        - include_stub_subckts?: bool (default: True)
        - kind_to_subckt?: object (default: autogenerated)

    Artifacts:
      - netlist.sp
      - spice_map.json
      - spice_provenance.json
    """

    if not isinstance(request, dict):
        raise TypeError("request must be an object")

    graph = request.get("graph")
    if not isinstance(graph, dict):
        raise TypeError("request.graph must be an object")
    validate_graph(graph, require_jsonschema=require_schema)
    if str(graph.get("profile", "")).strip().lower() != "pic_circuit":
        raise ValueError("export_pic_graph_to_spice_artifacts requires graph.profile=pic_circuit")

    settings = request.get("settings") if isinstance(request.get("settings"), dict) else {}
    top_name = _spice_ident(settings.get("top_name") or "PT_TOP")
    subckt_prefix = _spice_ident(settings.get("subckt_prefix") or "PT")
    include_stub_subckts = bool(settings.get("include_stub_subckts", True))
    kind_to_subckt = settings.get("kind_to_subckt") if isinstance(settings.get("kind_to_subckt"), dict) else {}

    compiled = compile_graph(graph, require_schema=require_schema)
    netlist = compiled.compiled

    # Build union-find over terminals (node, port).
    uf = _UF(parent={})

    # Ensure all node ports are in UF so floating pins get their own nets.
    node_kinds: dict[str, str] = {}
    for n in (netlist.get("nodes") or []):
        if not isinstance(n, dict):
            continue
        node_id = str(n.get("id", "")).strip()
        kind = str(n.get("kind", "")).strip().lower()
        if not node_id:
            continue
        node_kinds[node_id] = kind
        params = n.get("params", {}) or {}
        p = component_ports(kind, params=params)
        for port in list(p.in_ports) + list(p.out_ports):
            uf.find((node_id, str(port)))

    # Union terminals by edges.
    for e in (netlist.get("edges") or []):
        if not isinstance(e, dict):
            continue
        a = (str(e.get("from", "")).strip(), str(e.get("from_port", "out")))
        b = (str(e.get("to", "")).strip(), str(e.get("to_port", "in")))
        if not a[0] or not b[0]:
            continue
        uf.union(a, b)

    # Group terminals and assign deterministic net names.
    groups: dict[tuple[str, str], list[tuple[str, str]]] = {}
    for t in list(uf.parent.keys()):
        root = uf.find(t)
        groups.setdefault(root, []).append(t)

    net_by_terminal: dict[tuple[str, str], str] = {}
    net_groups_out = []
    for root, terms in sorted(groups.items(), key=lambda kv: (kv[0][0].lower(), kv[0][1].lower())):
        # Canonical name: smallest terminal.
        canon = sorted(terms, key=lambda t: (t[0].lower(), t[1].lower()))[0]
        net_name = _spice_ident(f"n_{canon[0]}_{canon[1]}")
        for t in terms:
            net_by_terminal[t] = net_name
        net_groups_out.append({"net": net_name, "terminals": [{"node": n, "port": p} for (n, p) in terms]})

    # Emit instance lines.
    used_subckts: dict[str, dict[str, Any]] = {}
    inst_lines = []
    for node_id in sorted(node_kinds.keys(), key=lambda s: s.lower()):
        kind = node_kinds[node_id]
        node = next((n for n in (netlist.get("nodes") or []) if isinstance(n, dict) and str(n.get("id")) == node_id), None)
        params = node.get("params", {}) if isinstance(node, dict) else {}
        if params is None:
            params = {}
        if not isinstance(params, dict):
            params = {}
        p = component_ports(kind, params=params)
        pin_terms = [(node_id, str(port)) for port in list(p.in_ports) + list(p.out_ports)]
        pins = [net_by_terminal.get(t, _spice_ident(f"n_{t[0]}_{t[1]}")) for t in pin_terms]

        default_subckt = _spice_ident(f"{subckt_prefix}_{kind.replace('.', '_')}")
        subckt = _spice_ident(kind_to_subckt.get(kind) or default_subckt)
        used_subckts.setdefault(subckt, {"kind": kind, "pins": [str(x) for x in list(p.in_ports) + list(p.out_ports)]})

        # Params: inline key=value (stringified) for auditability.
        params_items = []
        for k, v in sorted(params.items(), key=lambda kv: str(kv[0]).lower()):
            if v is None:
                continue
            params_items.append(f"{_spice_ident(k)}={v}")
        params_s = (" " + " ".join(params_items)) if params_items else ""

        inst = f"X{_spice_ident(node_id)} " + " ".join(pins) + f" {subckt}{params_s}"
        inst_lines.append(inst)

    # Build netlist text.
    generated_at = datetime.now(timezone.utc).isoformat()
    graph_hash = hash_dict(graph)
    header = [
        f"* PhotonTrust SPICE export v0.1",
        f"* generated_at={generated_at}",
        f"* graph_id={graph.get('graph_id')}",
        f"* graph_hash={graph_hash}",
        f".subckt {top_name}",
    ]
    footer = [f".ends {top_name}", ".end"]

    stub_subckts = []
    if include_stub_subckts:
        for subckt, meta in sorted(used_subckts.items(), key=lambda kv: kv[0].lower()):
            pins = meta.get("pins") or []
            if not isinstance(pins, list):
                pins = []
            pin_list = " ".join([_spice_ident(p) for p in pins])
            stub_subckts.extend(
                [
                    "",
                    f"* Stub subckt for kind={meta.get('kind')}",
                    f".subckt {subckt} {pin_list}",
                    f"* TODO: replace with foundry/EDA-provided compact model subcircuit",
                    f".ends {subckt}",
                ]
            )

    netlist_text = "\n".join(header + [""] + inst_lines + footer + stub_subckts + [""])

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    netlist_path = output_dir / "netlist.sp"
    netlist_path.write_text(netlist_text, encoding="utf-8")

    spice_map = {
        "schema_version": "0.1",
        "kind": "pic.spice_map",
        "top_name": top_name,
        "nets": net_groups_out,
        "instances": [
            {
                "node": node_id,
                "kind": node_kinds[node_id],
                "subckt": _spice_ident(
                    kind_to_subckt.get(node_kinds[node_id]) or f"{subckt_prefix}_{node_kinds[node_id].replace('.', '_')}"
                ),
            }
            for node_id in sorted(node_kinds.keys(), key=lambda s: s.lower())
        ],
    }
    map_path = output_dir / "spice_map.json"
    map_path.write_text(json.dumps(spice_map, indent=2), encoding="utf-8")

    provenance = {
        "schema_version": "0.1",
        "generated_at": generated_at,
        "graph_id": graph.get("graph_id"),
        "graph_hash": graph_hash,
        "toolchain": {"python": sys.version.split()[0], "platform": platform.platform()},
        "settings": {
            "top_name": top_name,
            "subckt_prefix": subckt_prefix,
            "include_stub_subckts": include_stub_subckts,
        },
        "artifacts": {
            "netlist_path": str(netlist_path.name),
            "spice_map_path": str(map_path.name),
        },
        "warnings": list(compiled.warnings or []),
    }
    prov_path = output_dir / "spice_provenance.json"
    prov_path.write_text(json.dumps(provenance, indent=2), encoding="utf-8")

    return {
        "schema_version": "0.1",
        "generated_at": generated_at,
        "graph_id": graph.get("graph_id"),
        "artifacts": {
            "netlist_path": str(netlist_path.name),
            "spice_map_path": str(map_path.name),
            "spice_provenance_path": str(prov_path.name),
        },
        "summary": {
            "instances": int(len(node_kinds)),
            "nets": int(len(net_groups_out)),
            "stub_subckts_included": bool(include_stub_subckts),
        },
        "warnings": list(compiled.warnings or []),
    }
