"""Kind registry (v0.1).

This module defines the backend-owned "component kind" catalog used by:
- the web editor trust panel (units, defaults, ranges),
- optional validation surfaces, and
- documentation generation (future).

The registry is deliberately lightweight: it is a descriptive contract and does
not execute physics.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from photonstrust.presets import BAND_PRESETS, DETECTOR_PRESETS


REGISTRY_SCHEMA_VERSION = "0.1"


@dataclass(frozen=True)
class _Missing:
    pass


_MISSING = _Missing()


def _param(
    name: str,
    typ: str,
    *,
    unit: str | None = None,
    required: bool = False,
    default: Any = _MISSING,
    minimum: float | None = None,
    maximum: float | None = None,
    enum: list[Any] | None = None,
    description: str = "",
    applies_when: dict[str, Any] | None = None,
) -> dict[str, Any]:
    out: dict[str, Any] = {
        "name": str(name),
        "type": str(typ),
        "required": bool(required),
        "description": str(description or ""),
    }
    if unit is not None:
        out["unit"] = str(unit)
    if default is not _MISSING:
        out["default"] = default
    if minimum is not None:
        out["min"] = float(minimum)
    if maximum is not None:
        out["max"] = float(maximum)
    if enum is not None:
        out["enum"] = list(enum)
    if applies_when is not None:
        out["applies_when"] = dict(applies_when)
    return out


def _kind(
    kind: str,
    *,
    title: str,
    category: str,
    in_ports: list[str],
    out_ports: list[str],
    in_port_domains: dict[str, str] | None = None,
    out_port_domains: dict[str, str] | None = None,
    params: list[dict[str, Any]],
    api_enabled: bool = True,
    cli_enabled: bool = True,
    notes: list[str] | None = None,
) -> dict[str, Any]:
    in_port_list = [str(p) for p in in_ports]
    out_port_list = [str(p) for p in out_ports]

    default_domain = "optical" if str(category).strip().lower() == "pic" else "control"
    in_domains = {port: str(default_domain) for port in in_port_list}
    out_domains = {port: str(default_domain) for port in out_port_list}
    if isinstance(in_port_domains, dict):
        for k, v in in_port_domains.items():
            in_domains[str(k)] = str(v)
    if isinstance(out_port_domains, dict):
        for k, v in out_port_domains.items():
            out_domains[str(k)] = str(v)

    out: dict[str, Any] = {
        "kind": str(kind),
        "title": str(title),
        "category": str(category),
        "ports": {"in": in_port_list, "out": out_port_list},
        "port_domains": {"in": in_domains, "out": out_domains},
        "params": list(params),
        "availability": {
            "api_enabled": bool(api_enabled),
            "cli_enabled": bool(cli_enabled),
        },
    }
    if notes:
        out["notes"] = [str(n) for n in notes]
    return out


def build_kinds_registry() -> dict[str, Any]:
    """Return the backend-owned kind registry dict."""

    detector_classes = sorted(DETECTOR_PRESETS.keys(), key=lambda s: str(s).lower())
    band_ids = sorted(BAND_PRESETS.keys(), key=lambda s: str(s).lower())

    kinds = [
        _kind(
            "qkd.source",
            title="Source",
            category="qkd",
            in_ports=[],
            out_ports=["out"],
            params=[
                _param(
                    "type",
                    "string",
                    required=True,
                    enum=["emitter_cavity", "spdc"],
                    default="emitter_cavity",
                    description="Source primitive family (controls which parameters apply).",
                ),
                _param(
                    "physics_backend",
                    "string",
                    required=False,
                    enum=["analytic", "qutip"],
                    default="analytic",
                    description="Backend for source physics. Analytic is fast; QuTiP is higher fidelity when installed.",
                ),
                _param(
                    "rep_rate_mhz",
                    "number",
                    unit="MHz",
                    required=False,
                    default=100,
                    minimum=0.0,
                    description="Repetition rate of the source pump/trigger.",
                ),
                _param(
                    "collection_efficiency",
                    "number",
                    unit="fraction",
                    required=False,
                    default=0.35,
                    minimum=0.0,
                    maximum=1.0,
                    description="Collection efficiency from emitter into the guided/usable mode.",
                ),
                _param(
                    "coupling_efficiency",
                    "number",
                    unit="fraction",
                    required=False,
                    default=0.60,
                    minimum=0.0,
                    maximum=1.0,
                    description="Coupling efficiency into the channel (e.g., fiber coupling).",
                ),
                _param(
                    "hom_visibility",
                    "number",
                    unit="fraction",
                    required=False,
                    default=None,
                    minimum=0.0,
                    maximum=1.0,
                    description="Optional HOM visibility proxy (used as a source-visibility QBER/fidelity floor).",
                ),
                _param(
                    "indistinguishability",
                    "number",
                    unit="fraction",
                    required=False,
                    default=None,
                    minimum=0.0,
                    maximum=1.0,
                    description="Alias for hom_visibility (pick one).",
                ),
                _param(
                    "emission_mode",
                    "string",
                    required=False,
                    enum=["steady_state", "transient"],
                    default="steady_state",
                    description="Emission mode for cavity-like sources (steady-state vs pulse-resolved transient).",
                    applies_when={"type": "emitter_cavity"},
                ),
                _param(
                    "radiative_lifetime_ns",
                    "number",
                    unit="ns",
                    required=False,
                    default=1.0,
                    minimum=0.0,
                    description="Radiative lifetime parameter for emitter-cavity model.",
                    applies_when={"type": "emitter_cavity"},
                ),
                _param(
                    "purcell_factor",
                    "number",
                    required=False,
                    default=5.0,
                    minimum=0.0,
                    description="Purcell enhancement factor (emitter-cavity).",
                    applies_when={"type": "emitter_cavity"},
                ),
                _param(
                    "dephasing_rate_per_ns",
                    "number",
                    unit="1/ns",
                    required=False,
                    default=0.5,
                    minimum=0.0,
                    description="Pure dephasing rate (emitter-cavity).",
                    applies_when={"type": "emitter_cavity"},
                ),
                _param(
                    "g2_0",
                    "number",
                    required=False,
                    default=0.02,
                    minimum=0.0,
                    description="Second-order correlation at zero delay (multi-photon impurity proxy).",
                    applies_when={"type": "emitter_cavity"},
                ),
                _param(
                    "drive_strength",
                    "number",
                    required=False,
                    default=0.05,
                    minimum=0.0,
                    description="Drive/pump strength (dimensionless proxy, model-specific).",
                    applies_when={"type": "emitter_cavity"},
                ),
                _param(
                    "pulse_window_ns",
                    "number",
                    unit="ns",
                    required=False,
                    default=5.0,
                    minimum=0.0,
                    description="Transient integration window (emitter-cavity).",
                    applies_when={"type": "emitter_cavity"},
                ),
                _param(
                    "transient_steps",
                    "integer",
                    required=False,
                    default=64,
                    minimum=1.0,
                    description="Number of time steps used for transient diagnostics (emitter-cavity).",
                    applies_when={"type": "emitter_cavity"},
                ),
                _param(
                    "mu",
                    "number",
                    required=False,
                    default=0.05,
                    minimum=0.0,
                    description="Mean photon pair number for SPDC-like source models.",
                    applies_when={"type": "spdc"},
                ),
            ],
        ),
        _kind(
            "qkd.channel",
            title="Channel",
            category="qkd",
            in_ports=["in"],
            out_ports=["out"],
            params=[
                _param(
                    "model",
                    "string",
                    required=False,
                    enum=["fiber", "free_space"],
                    default="fiber",
                    description="Channel model family.",
                ),
                _param(
                    "fiber_loss_db_per_km",
                    "number",
                    unit="dB/km",
                    required=False,
                    default=None,
                    minimum=0.0,
                    description="Fiber attenuation coefficient. If null, band preset is used.",
                    applies_when={"model": "fiber"},
                ),
                _param(
                    "dispersion_ps_per_km",
                    "number",
                    unit="ps/km",
                    required=False,
                    default=None,
                    minimum=0.0,
                    description="Fiber dispersion proxy. If null, band preset is used.",
                    applies_when={"model": "fiber"},
                ),
                _param(
                    "connector_loss_db",
                    "number",
                    unit="dB",
                    required=False,
                    default=1.5,
                    minimum=0.0,
                    description="Lumped insertion loss at interfaces/connectors.",
                ),
                _param(
                    "polarization_coherence_length_km",
                    "number",
                    unit="km",
                    required=False,
                    minimum=0.0,
                    description="If set, applies a polarization drift penalty vs distance.",
                    applies_when={"model": "fiber"},
                ),
                _param(
                    "elevation_deg",
                    "number",
                    unit="deg",
                    required=False,
                    default=45.0,
                    minimum=0.0,
                    maximum=90.0,
                    description="Elevation angle for free-space geometry (simplified model).",
                    applies_when={"model": "free_space"},
                ),
                _param(
                    "tx_aperture_m",
                    "number",
                    unit="m",
                    required=False,
                    default=0.12,
                    minimum=0.0,
                    description="Transmitter aperture diameter (free-space).",
                    applies_when={"model": "free_space"},
                ),
                _param(
                    "rx_aperture_m",
                    "number",
                    unit="m",
                    required=False,
                    default=0.30,
                    minimum=0.0,
                    description="Receiver aperture diameter (free-space).",
                    applies_when={"model": "free_space"},
                ),
                _param(
                    "beam_divergence_urad",
                    "number",
                    unit="urad",
                    required=False,
                    default=None,
                    minimum=0.0,
                    description="Beam divergence (if null, inferred from wavelength and TX aperture).",
                    applies_when={"model": "free_space"},
                ),
                _param(
                    "pointing_jitter_urad",
                    "number",
                    unit="urad",
                    required=False,
                    default=1.5,
                    minimum=0.0,
                    description="Pointing jitter standard deviation (free-space).",
                    applies_when={"model": "free_space"},
                ),
                _param(
                    "atmospheric_extinction_db_per_km",
                    "number",
                    unit="dB/km",
                    required=False,
                    default=0.02,
                    minimum=0.0,
                    description="Atmospheric extinction coefficient (free-space).",
                    applies_when={"model": "free_space"},
                ),
                _param(
                    "turbulence_scintillation_index",
                    "number",
                    required=False,
                    default=0.15,
                    minimum=0.0,
                    description="Simple turbulence penalty proxy (0..).",
                    applies_when={"model": "free_space"},
                ),
                _param(
                    "background_counts_cps",
                    "number",
                    unit="counts/s",
                    required=False,
                    default=0.0,
                    minimum=0.0,
                    description="Background counts added into the detector noise model (fiber/free-space).",
                ),
                _param(
                    "coexistence",
                    "object",
                    required=False,
                    default={"enabled": False},
                    description="Optional fiber coexistence noise model configuration (e.g., Raman background).",
                    applies_when={"model": "fiber"},
                ),
            ],
        ),
        _kind(
            "qkd.detector",
            title="Detector",
            category="qkd",
            in_ports=["in"],
            out_ports=[],
            params=[
                _param(
                    "class",
                    "string",
                    required=True,
                    enum=detector_classes,
                    default="snspd",
                    description="Detector class preset name.",
                ),
                _param(
                    "physics_backend",
                    "string",
                    required=False,
                    enum=["analytic", "stochastic"],
                    default="analytic",
                    description="Detector model backend (analytic vs stochastic sampling).",
                ),
                _param(
                    "pde",
                    "number",
                    unit="fraction",
                    required=False,
                    default=None,
                    minimum=0.0,
                    maximum=1.0,
                    description="Photon detection efficiency. If null, detector preset is used.",
                ),
                _param(
                    "dark_counts_cps",
                    "number",
                    unit="counts/s",
                    required=False,
                    default=None,
                    minimum=0.0,
                    description="Dark count rate. If null, detector preset is used.",
                ),
                _param(
                    "background_counts_cps",
                    "number",
                    unit="counts/s",
                    required=False,
                    default=0.0,
                    minimum=0.0,
                    description="Additional background count rate injected into the detector model (e.g., ambient/leakage).",
                ),
                _param(
                    "jitter_ps_fwhm",
                    "number",
                    unit="ps (FWHM)",
                    required=False,
                    default=None,
                    minimum=0.0,
                    description="Timing jitter full-width at half maximum. If null, detector preset is used.",
                ),
                _param(
                    "dead_time_ns",
                    "number",
                    unit="ns",
                    required=False,
                    default=None,
                    minimum=0.0,
                    description="Dead time after a click. If null, detector preset is used.",
                ),
                _param(
                    "dead_time_model",
                    "string",
                    required=False,
                    enum=["nonparalyzable", "paralyzable", "legacy"],
                    default="nonparalyzable",
                    description="Dead-time saturation model (non-paralyzable default).",
                ),
                _param(
                    "afterpulsing_prob",
                    "number",
                    unit="fraction",
                    required=False,
                    default=None,
                    minimum=0.0,
                    maximum=1.0,
                    description="Afterpulsing probability. If null, detector preset is used.",
                ),
                _param(
                    "sample_count",
                    "integer",
                    required=False,
                    default=500,
                    minimum=1.0,
                    description="Base sample count for stochastic detector backend.",
                    applies_when={"physics_backend": "stochastic"},
                ),
                _param(
                    "time_bin_ps",
                    "number",
                    unit="ps",
                    required=False,
                    default=10.0,
                    minimum=0.0,
                    description="Detector histogram/bin time resolution for stochastic backend.",
                    applies_when={"physics_backend": "stochastic"},
                ),
                _param(
                    "afterpulse_delay_ns",
                    "number",
                    unit="ns",
                    required=False,
                    default=50.0,
                    minimum=0.0,
                    description="Afterpulse delay proxy for stochastic backend.",
                    applies_when={"physics_backend": "stochastic"},
                ),
            ],
        ),
        _kind(
            "qkd.timing",
            title="Timing",
            category="qkd",
            in_ports=[],
            out_ports=[],
            params=[
                _param(
                    "sync_drift_ps_rms",
                    "number",
                    unit="ps (RMS)",
                    required=False,
                    default=10.0,
                    minimum=0.0,
                    description="Synchronization drift RMS.",
                ),
                _param(
                    "coincidence_window_ps",
                    "number",
                    unit="ps",
                    required=False,
                    default=None,
                    minimum=0.0,
                    description="Coincidence window. If null, auto-sized from jitter/drift/dispersion.",
                ),
            ],
        ),
        _kind(
            "qkd.protocol",
            title="Protocol",
            category="qkd",
            in_ports=[],
            out_ports=[],
            params=[
                _param(
                    "name",
                    "string",
                    required=False,
                    enum=["BBM92", "E91", "MDI_QKD", "AMDI_QKD", "PM_QKD", "TF_QKD"],
                    default="BBM92",
                    description="Protocol family label (used for reporting/metadata).",
                ),
                _param(
                    "relay_fraction",
                    "number",
                    unit="fraction",
                    required=False,
                    default=0.5,
                    minimum=0.0,
                    maximum=1.0,
                    description="Relay split for relay-based protocols (Alice->relay distance fraction).",
                ),
                _param(
                    "mu",
                    "number",
                    unit="photons/pulse",
                    required=False,
                    default=None,
                    minimum=0.0,
                    description="Signal intensity (required for MDI_QKD/AMDI_QKD and PM_QKD/TF_QKD).",
                ),
                _param(
                    "nu",
                    "number",
                    unit="photons/pulse",
                    required=False,
                    default=None,
                    minimum=0.0,
                    description="Decoy intensity nu (required for MDI_QKD/AMDI_QKD).",
                ),
                _param(
                    "omega",
                    "number",
                    unit="photons/pulse",
                    required=False,
                    default=0.0,
                    minimum=0.0,
                    description="Vacuum/weak decoy intensity omega (MDI_QKD/AMDI_QKD; defaults to 0).",
                ),
                _param(
                    "mu_a",
                    "number",
                    unit="photons/pulse",
                    required=False,
                    default=None,
                    minimum=0.0,
                    description="Optional asymmetric signal intensity for Alice (MDI_QKD/AMDI_QKD).",
                ),
                _param(
                    "mu_b",
                    "number",
                    unit="photons/pulse",
                    required=False,
                    default=None,
                    minimum=0.0,
                    description="Optional asymmetric signal intensity for Bob (MDI_QKD/AMDI_QKD).",
                ),
                _param(
                    "nu_a",
                    "number",
                    unit="photons/pulse",
                    required=False,
                    default=None,
                    minimum=0.0,
                    description="Optional asymmetric decoy intensity for Alice (MDI_QKD/AMDI_QKD).",
                ),
                _param(
                    "nu_b",
                    "number",
                    unit="photons/pulse",
                    required=False,
                    default=None,
                    minimum=0.0,
                    description="Optional asymmetric decoy intensity for Bob (MDI_QKD/AMDI_QKD).",
                ),
                _param(
                    "omega_a",
                    "number",
                    unit="photons/pulse",
                    required=False,
                    default=None,
                    minimum=0.0,
                    description="Optional asymmetric omega for Alice (MDI_QKD/AMDI_QKD).",
                ),
                _param(
                    "omega_b",
                    "number",
                    unit="photons/pulse",
                    required=False,
                    default=None,
                    minimum=0.0,
                    description="Optional asymmetric omega for Bob (MDI_QKD/AMDI_QKD).",
                ),
                _param(
                    "pairing_window_bins",
                    "number",
                    required=False,
                    default=2048.0,
                    minimum=1.0,
                    description="Asynchronous pairing window length (AMDI_QKD).",
                    applies_when={"name": "AMDI_QKD"},
                ),
                _param(
                    "pairing_efficiency",
                    "number",
                    unit="fraction",
                    required=False,
                    default=0.6,
                    minimum=0.0,
                    maximum=1.0,
                    description="Usable asynchronous-pair fraction in AMDI_QKD.",
                    applies_when={"name": "AMDI_QKD"},
                ),
                _param(
                    "pairing_error_prob",
                    "number",
                    unit="fraction",
                    required=False,
                    default=0.0,
                    minimum=0.0,
                    maximum=0.5,
                    description="Additional random-pairing error probability in AMDI_QKD.",
                    applies_when={"name": "AMDI_QKD"},
                ),
                _param(
                    "pairing_gain_max",
                    "number",
                    required=False,
                    default=1.0e6,
                    minimum=1.0,
                    description="Hard cap for asynchronous pairing gain in AMDI_QKD.",
                    applies_when={"name": "AMDI_QKD"},
                ),
                _param(
                    "phase_slices",
                    "number",
                    required=False,
                    default=16,
                    minimum=2.0,
                    description="Number of phase slices M used in PM_QKD/TF_QKD post-compensation (Appendix B.2).",
                ),
                _param(
                    "ed1",
                    "number",
                    unit="fraction",
                    required=False,
                    default=None,
                    minimum=0.0,
                    maximum=0.5,
                    description="Optional per-channel misalignment proxy used in Xu (MDI_QKD) Appendix B.2.",
                ),
                _param(
                    "sifting_factor",
                    "number",
                    required=False,
                    default=0.5,
                    minimum=0.0,
                    maximum=1.0,
                    description="Basis sifting factor (fraction of raw events kept).",
                ),
                _param(
                    "ec_efficiency",
                    "number",
                    required=False,
                    default=1.16,
                    minimum=1.0,
                    description="Error correction inefficiency factor f_EC >= 1.",
                ),
                _param(
                    "misalignment_prob",
                    "number",
                    unit="fraction",
                    required=False,
                    default=0.0,
                    minimum=0.0,
                    maximum=0.5,
                    description="Explicit misalignment/visibility QBER floor (probability).",
                ),
                _param(
                    "optical_visibility",
                    "number",
                    unit="fraction",
                    required=False,
                    default=None,
                    minimum=0.0,
                    maximum=1.0,
                    description="Alternative to misalignment_prob: QBER floor computed as (1-visibility)/2.",
                ),
                _param(
                    "key_rate_floor_bps",
                    "number",
                    unit="bps",
                    required=False,
                    default=0.0,
                    minimum=0.0,
                    description="Outage threshold used in uncertainty/outage reporting.",
                ),
            ],
        ),
        _kind(
            "pic.grating_coupler",
            title="Grating Coupler",
            category="pic",
            in_ports=["in"],
            out_ports=["out"],
            params=[
                _param(
                    "insertion_loss_db",
                    "number",
                    unit="dB",
                    required=False,
                    default=2.5,
                    minimum=0.0,
                    description="Insertion loss of the coupler (power) in dB.",
                ),
                _param(
                    "return_loss_db",
                    "number",
                    unit="dB",
                    required=False,
                    default=None,
                    minimum=0.0,
                    description="Optional port return loss (scattering solver: sets S11/S22 magnitude).",
                ),
                _param(
                    "reflection_phase_rad",
                    "number",
                    unit="rad",
                    required=False,
                    default=0.0,
                    description="Optional reflection phase used with return_loss_db (scattering solver).",
                ),
            ],
        ),
        _kind(
            "pic.edge_coupler",
            title="Edge Coupler",
            category="pic",
            in_ports=["in"],
            out_ports=["out"],
            params=[
                _param(
                    "insertion_loss_db",
                    "number",
                    unit="dB",
                    required=False,
                    default=1.5,
                    minimum=0.0,
                    description="Insertion loss of the coupler (power) in dB.",
                ),
                _param(
                    "return_loss_db",
                    "number",
                    unit="dB",
                    required=False,
                    default=None,
                    minimum=0.0,
                    description="Optional port return loss (scattering solver: sets S11/S22 magnitude).",
                ),
                _param(
                    "reflection_phase_rad",
                    "number",
                    unit="rad",
                    required=False,
                    default=0.0,
                    description="Optional reflection phase used with return_loss_db (scattering solver).",
                ),
            ],
        ),
        _kind(
            "pic.waveguide",
            title="Waveguide",
            category="pic",
            in_ports=["in"],
            out_ports=["out"],
            params=[
                _param(
                    "length_um",
                    "number",
                    unit="um",
                    required=True,
                    default=2000.0,
                    minimum=0.0,
                    description="Physical waveguide length.",
                ),
                _param(
                    "loss_db_per_cm",
                    "number",
                    unit="dB/cm",
                    required=False,
                    default=2.0,
                    minimum=0.0,
                    description="Propagation loss coefficient.",
                ),
                _param(
                    "n_eff",
                    "number",
                    required=False,
                    default=None,
                    minimum=0.0,
                    description="Effective index (optional). If provided and phase_rad is absent, phase can be inferred vs wavelength.",
                ),
                _param(
                    "phase_rad",
                    "number",
                    unit="rad",
                    required=False,
                    default=None,
                    description="Optional explicit phase. Overrides n_eff-based inference when set.",
                ),
                _param(
                    "return_loss_db",
                    "number",
                    unit="dB",
                    required=False,
                    default=None,
                    minimum=0.0,
                    description="Optional port return loss (scattering solver: sets S11/S22 magnitude).",
                ),
                _param(
                    "reflection_phase_rad",
                    "number",
                    unit="rad",
                    required=False,
                    default=0.0,
                    description="Optional reflection phase used with return_loss_db (scattering solver).",
                ),
            ],
        ),
        _kind(
            "pic.phase_shifter",
            title="Phase Shifter",
            category="pic",
            in_ports=["in"],
            out_ports=["out"],
            params=[
                _param(
                    "phase_rad",
                    "number",
                    unit="rad",
                    required=False,
                    default=0.0,
                    description="Applied phase shift.",
                ),
                _param(
                    "insertion_loss_db",
                    "number",
                    unit="dB",
                    required=False,
                    default=0.1,
                    minimum=0.0,
                    description="Insertion loss in dB.",
                ),
                _param(
                    "return_loss_db",
                    "number",
                    unit="dB",
                    required=False,
                    default=None,
                    minimum=0.0,
                    description="Optional port return loss (scattering solver: sets S11/S22 magnitude).",
                ),
                _param(
                    "reflection_phase_rad",
                    "number",
                    unit="rad",
                    required=False,
                    default=0.0,
                    description="Optional reflection phase used with return_loss_db (scattering solver).",
                ),
            ],
        ),
        _kind(
            "pic.isolator_2port",
            title="Isolator (2-port)",
            category="pic",
            in_ports=["in"],
            out_ports=["out"],
            params=[
                _param(
                    "insertion_loss_db",
                    "number",
                    unit="dB",
                    required=False,
                    default=1.0,
                    minimum=0.0,
                    description="Forward insertion loss (power) in dB.",
                ),
                _param(
                    "phase_rad",
                    "number",
                    unit="rad",
                    required=False,
                    default=0.0,
                    description="Optional forward phase.",
                ),
                _param(
                    "isolation_db",
                    "number",
                    unit="dB",
                    required=False,
                    default=30.0,
                    minimum=0.0,
                    description="Additional reverse-path attenuation (dB). Reverse loss defaults to insertion_loss_db + isolation_db.",
                ),
                _param(
                    "reverse_phase_rad",
                    "number",
                    unit="rad",
                    required=False,
                    default=None,
                    description="Optional reverse phase (defaults to forward phase).",
                ),
                _param(
                    "return_loss_db",
                    "number",
                    unit="dB",
                    required=False,
                    default=None,
                    minimum=0.0,
                    description="Optional port return loss (scattering solver: sets S11/S22 magnitude).",
                ),
                _param(
                    "reflection_phase_rad",
                    "number",
                    unit="rad",
                    required=False,
                    default=0.0,
                    description="Optional reflection phase used with return_loss_db (scattering solver).",
                ),
            ],
        ),
        _kind(
            "pic.ring",
            title="Ring (All-Pass, v0.2)",
            category="pic",
            in_ports=["in"],
            out_ports=["out"],
            params=[
                _param(
                    "coupling_ratio",
                    "number",
                    unit="fraction",
                    required=False,
                    default=0.002,
                    minimum=0.0,
                    maximum=1.0,
                    description="Power coupling ratio (kappa) for the bus-to-ring coupler (all-pass model).",
                ),
                _param(
                    "radius_um",
                    "number",
                    unit="um",
                    required=False,
                    default=10.0,
                    minimum=0.0,
                    description="Ring radius (um). Used to compute round-trip length = 2*pi*radius.",
                ),
                _param(
                    "round_trip_length_um",
                    "number",
                    unit="um",
                    required=False,
                    default=None,
                    minimum=0.0,
                    description="Optional override for the round-trip length (um). If set, takes precedence over radius_um.",
                ),
                _param(
                    "n_eff",
                    "number",
                    unit="",
                    required=False,
                    default=2.4,
                    minimum=0.0,
                    description="Effective index used to compute round-trip phase vs wavelength.",
                ),
                _param(
                    "loss_db_per_cm",
                    "number",
                    unit="dB/cm",
                    required=False,
                    default=2.0,
                    minimum=0.0,
                    description="Propagation loss (power) used to compute round-trip amplitude transmission.",
                ),
                _param(
                    "insertion_loss_db",
                    "number",
                    unit="dB",
                    required=False,
                    default=0.0,
                    minimum=0.0,
                    description="Optional extra insertion loss on the bus (applied outside the resonator transfer).",
                ),
                _param(
                    "return_loss_db",
                    "number",
                    unit="dB",
                    required=False,
                    default=None,
                    minimum=0.0,
                    description="Optional port return loss (scattering solver: sets S11/S22 magnitude).",
                ),
                _param(
                    "reflection_phase_rad",
                    "number",
                    unit="rad",
                    required=False,
                    default=0.0,
                    description="Optional reflection phase used with return_loss_db (scattering solver).",
                ),
            ],
            notes=[
                "v0.2 ring implements an all-pass 2-port transfer function (forward-only, no explicit feedback loop solving).",
                "Backwards compatibility: if only insertion_loss_db is provided, ring behaves like the v0.1 lumped-loss placeholder.",
            ],
        ),
        _kind(
            "pic.coupler",
            title="2x2 Coupler",
            category="pic",
            in_ports=["in1", "in2"],
            out_ports=["out1", "out2"],
            params=[
                _param(
                    "coupling_ratio",
                    "number",
                    unit="fraction",
                    required=False,
                    default=0.5,
                    minimum=0.0,
                    maximum=1.0,
                    description="Power coupling ratio (kappa).",
                ),
                _param(
                    "insertion_loss_db",
                    "number",
                    unit="dB",
                    required=False,
                    default=0.2,
                    minimum=0.0,
                    description="Insertion loss in dB.",
                ),
            ],
        ),
        _kind(
            "pic.touchstone_2port",
            title="Touchstone 2-port (S2P)",
            category="pic",
            in_ports=["in"],
            out_ports=["out"],
            api_enabled=False,
            cli_enabled=True,
            params=[
                _param(
                    "touchstone_path",
                    "string",
                    required=False,
                    description="Path to a Touchstone .s2p file (CLI workflows).",
                ),
                _param(
                    "path",
                    "string",
                    required=False,
                    description="Alias for touchstone_path (CLI workflows).",
                ),
                _param(
                    "forward",
                    "string",
                    required=False,
                    enum=["s21", "s12"],
                    default="s21",
                    description="Which S-parameter is used as the forward transfer.",
                ),
                _param(
                    "allow_extrapolation",
                    "boolean",
                    required=False,
                    default=False,
                    description="If true, allow extrapolation outside frequency bounds (not recommended for certification).",
                ),
            ],
            notes=[
                "Disabled in API server by default (would require server-side file reads).",
                "Use CLI workflows for Touchstone import and sweeps.",
            ],
        ),
        _kind(
            "pic.touchstone_nport",
            title="Touchstone N-port (SNP)",
            category="pic",
            in_ports=[],
            out_ports=[],
            api_enabled=False,
            cli_enabled=True,
            params=[
                _param(
                    "touchstone_path",
                    "string",
                    required=False,
                    description="Path to a Touchstone .sNp file (CLI workflows).",
                ),
                _param(
                    "path",
                    "string",
                    required=False,
                    description="Alias for touchstone_path (CLI workflows).",
                ),
                _param(
                    "n_ports",
                    "integer",
                    required=False,
                    default=None,
                    minimum=1.0,
                    description="Port count. If omitted, inferred from filename extension (.s4p -> 4).",
                ),
                _param(
                    "in_ports",
                    "array",
                    required=False,
                    default=None,
                    description="Array of input port names (e.g., ['p1','p2']). Required for odd n_ports; otherwise defaults to first half.",
                ),
                _param(
                    "out_ports",
                    "array",
                    required=False,
                    default=None,
                    description="Array of output port names (e.g., ['p3','p4']). Required for odd n_ports; otherwise defaults to second half.",
                ),
                _param(
                    "allow_extrapolation",
                    "boolean",
                    required=False,
                    default=False,
                    description="If true, allow extrapolation outside frequency bounds (not recommended for certification).",
                ),
            ],
            notes=[
                "Ports are dynamic and derived from params + n_ports (or inferred from filename).",
                "Port naming convention is p1..pN to match Touchstone port numbers.",
                "Disabled in API server by default (would require server-side file reads).",
            ],
        ),
    ]

    kinds.sort(key=lambda k: str(k.get("kind", "")).lower())
    return {"schema_version": REGISTRY_SCHEMA_VERSION, "kinds": kinds, "bands": band_ids}
